# Generated by Django 3.2.3 on 2023-08-11 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0007_auto_20230809_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carts',
            field=models.ManyToManyField(related_name='recipes_carts', through='recipes.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='recipes_favorites', through='recipes.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Список избранного'),
        ),
    ]
