# Generated by Django 3.2.3 on 2023-08-11 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0008_auto_20230811_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='carts',
            field=models.ManyToManyField(related_name='recipes_in_shopping_cart', through='recipes.ShoppingCart', to=settings.AUTH_USER_MODEL, verbose_name='Список покупок'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_recipes', through='recipes.Favorite', to=settings.AUTH_USER_MODEL, verbose_name='Список избранного'),
        ),
    ]
