# Generated by Django 3.2.3 on 2023-08-20 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20230811_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='carts',
            new_name='who_buys',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='favorites',
            new_name='who_likes',
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe'),
        ),
    ]
