# Generated by Django 3.2.3 on 2023-07-25 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': ('Пользователь',), 'verbose_name_plural': ('Пользователи',)},
        ),
    ]
